config/routes.rb
Rails.application.routes.draw do

  resources :todos

  resources :users, only: [] do
    member do
      get 'dashboard'
      get 'feeds_count'
    end
  end

  resources :news_items, except: [:edit, :update] do
    resources :comments, only: [:create, :index]
  end


  devise_for :users

  # root to: "users#dashboard"
  root to: "todos#index"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :news_item

  validates :body, presence: true

  scope :with_user,
    -> { joins(:user).select('comments.id, comments.body, users.email AS user_email')
      .order('comments.created_at DESC')}
end

app/models/news_feed.rb
class NewsFeed < ActiveRecord::Base
  belongs_to :user
  belongs_to :news_item

  validates_presence_of :user, :news_item
  validates :user_id, uniqueness: { scope: :news_item_id }

  scope :read, -> { where(status: true) }
  scope :unread, -> { where(status: false) }
end

app/models/news_feed_decorator.rb
#require 'delegate'

class NewsFeedDecorator# < SimpleDelegator

  def initialize(news_feed)
    @news_feed = news_feed
  end

  def news_status_class
    @news_feed.status.to_s == 'f' ? 'active fontBold' : ''
  end

  def news_status
    @news_feed.status.to_s == 'f' ? 'Unread' : 'Read'
  end

end

app/models/news_item.rb
class NewsItem < ActiveRecord::Base
  has_many :news_feeds
  has_many :comments, dependent: :destroy

  validates :body, presence: true
  validates :user_id, presence: true

  scope :with_user, ->(user_id) {
    joins(:news_feeds)
    .where('news_feeds.user_id = ?', user_id)
    .select('news_items.id, news_items.body, news_feeds.status AS status')
  }

  def comments_with_user
    comments.with_user
  end

  def update_news_feed!(current_user_id)
    news_feed = news_feeds.where(user_id: current_user_id).first
    news_feed && news_feed.update(status: true)
  end

  def create_feeds
    transaction do
      User.select(:id).find_each(batch_size: 100).map do |user|
        news_feeds.create(user_id: user.id)
      end
    end

    # self.class.connection.execute <<-EOS
    #   INSERT INTO news_feeds (`news_item_id`, `user_id`) VALUES #{feed_values.join(", ")}
    # EOS
  end

end

app/models/todo.rb
class Todo < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :news_items, through: :news_feeds
  has_many :news_feeds
  has_many :comments, dependent: :destroy

  def unread_news_count
    news_feeds.unread.count
  end

  def read_news_count
    news_feeds.read.count
  end

  def news_author?(news_item)
    news_item.user_id == self.id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def index
    news_item = get_news_item
    render json: news_item.comments_with_user
  end

  def create
    news_item = get_news_item
    comment   = news_item.comments.new(comments_param)
    if comment.save
      render json: {user_email: current_user.email, comment_body: comment.body}
    else
      render json: {error_message: comment.errors.full_messages}, status: :internal_server_error
    end
  end

  private

  def comments_param
    params.require(:comment).permit(:body, :user_id)
  end

  def get_news_item
    NewsItem.find(params[:news_item_id])
  end
end

app/controllers/news_items_controller.rb
class NewsItemsController < ApplicationController
  before_action :authenticate_user!

  def index
    @news_items = NewsItem.with_user(current_user.id)
  end

  def new
    @news_item = NewsItem.new(user_id: current_user.id)
  end

  def create
    @news_item = NewsItem.new(news_item_params)
    if @news_item.save
      @news_item.create_feeds
      redirect_to root_url
    else
      render :new
    end
  end

  def show
    @news_item = NewsItem.find(params[:id])
    @news_item.update_news_feed!(current_user.id)
    @comment = @news_item.comments.new(user_id: current_user.id)
  end

  def destroy
    @news_item = NewsItem.find(params[:id])
    @news_item.destroy if current_user.news_author?(@news_item)
    redirect_to root_url
  end

  private

  def news_item_params
    params[:news_item][:user_id] = current_user.id
    params.require(:news_item).permit(:body, :user_id)
  end

end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.all
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: 'Todo was successfully created.' }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params.require(:todo).permit(:name, :status)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def dashboard
    @unread_news = current_user.unread_news_count
    @read_news   = current_user.read_news_count
  end

  def feeds_count
    render json: {
      unread_news_count: current_user.unread_news_count,
      read_news_count: current_user.read_news_count
    }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def news_item_status(status)
    status.to_s == 'f' ? 'Unread' : 'Read'
  end

  def news_item_class(status)
    status.to_s == 'f' ? 'active fontBold' : ''
  end
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Svasth</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css">
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.min.css">
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
</head>
<body>
  <!-- Fixed navbar -->
  <div class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Svasth", root_url, class: "navbar-brand" %>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to "Home", root_url %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= link_to_if current_user, "Sign Out", destroy_user_session_url %>
          </li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/news_items/index.html.erb
<div class="panel">
  <div class="panel-heading">
    <h2>News List</h2>
  </div>

  <div class="panel-body table-responsive">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>#</th>
          <th>News</th>
          <th>Status</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
      <% @news_items.each_with_index do |news_item, index| %>
        <tr class="<%= news_item_class(news_item.status) %>">
          <td><%= index+1 %></td>
          <td><%= news_item.body.truncate(50, omission: '... (continued)') %></td>
          <td><%= news_item_status(news_item.status) %></td>
          <td><%= link_to "Show News", news_item_url(news_item)%></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/news_items/new.html.erb
<% if @news_item.errors.any? %>
<div class="panel">
  <div class="panel-heading">
    <h3>Failed to save news</h3>
  </div>

  <div class="panel-body">
    <% @news_item.errors.full_messages.each do |error| %>
      <span class="text-danger">* <%= error %></span>
    <% end %>
  </div>
</div>
<% end %>

<div class="panel">
  <div class="panel-heading">
    <h2>Add News</h2>
  </div>

  <div class="panel-body">
    <%= form_for @news_item,  class: "form-horizontal"  do |f| %>
      <div class="form-group">
        <%= f.label :body, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
          <%= f.text_area :body, class: "form-control", rows: "10" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10 mt20">
          <%= f.submit 'Create', class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/news_items/show.html.erb
<%= javascript_include_tag 'comments' %>

<div class="panel">
  <div class="panel-heading">
    <h2>News</h2>
    <% if current_user.news_author?(@news_item) %>
      <span class="text-muted">
        <%= link_to "Delete News", news_item_url(@news_item), method: :delete, data: { confirm: "You sure?" } %>
      </span>
    <% end %>
  </div>

  <div class="panel-body">
    <p><%= @news_item.body %></p>

    <!-- Comments Panel -->
    <div class="panel">
      <div class="panel-heading">
        <h4>Add Comment</h4>
        <%= form_for [@news_item, @comment], remote: true, class: "form-horizontal"  do |f| %>
          <%= f.hidden_field :user_id %>
          <div class="form-group">
            <%= f.text_area :body, class: "form-control", rows: "3" %>
          </div>
          <div class="form-group">
            <%= f.submit 'Add', class: "btn btn-default" %>
          </div>
        <% end %>
      </div>
      <div class="panel-body">
        <h4>Comments</h4>
        <div id="comment_section">
          <% Comment.with_user.each do | comment | %>
            <p><%= comment.body %> - <%= comment.user_email %></p>
          <% end %>
        </div>
      </div>
    </div>
    <!-- Comments Panel -->
  </div>
</div>

app/views/todos/_form.html.erb
<%= form_for(@todo) do |f| %>
  <% if @todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% @todo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.check_box :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todos/edit.html.erb
<h1>Editing todo</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

app/views/todos/index.html.erb
<%= javascript_include_tag 'todos' %>
<h1>Listing todos</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todos.each do |todo| %>
      <tr>
        <td><%= todo.name %></td>
        <td><%= todo.status %></td>
        <td><%= link_to 'Show', todo %></td>
        <td><%= link_to 'Edit', edit_todo_path(todo) %></td>
        <td><%= link_to 'Destroy', todo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todo', new_todo_path %>

app/views/todos/new.html.erb
<h1>New todo</h1>

<%= render 'form' %>

<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @todo.name %>
</p>

<p>
  <strong>Status:</strong>
  <%= @todo.status %>
</p>

<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>

app/views/users/dashboard.html.erb
<%= javascript_include_tag "dashboard" %>

<div class="page-header" data-user-id="<%= current_user.id %>">
  <h1>Dashboard</h1>
  <span class='mr10'><%= link_to "Show All News", news_items_url %></span> |
  <span class='ml10'><%= link_to "Add News", new_news_item_url %></span>
</div>

<div class="row">
  <div class="col-sm-9 col-md-10 col-md-offset-1 main">
    <div class="row placeholders">
      <div class="col-lg-6" id="unread-news">
        <span class="text-danger fs50"><%= @unread_news %></span>
        <h4>Unread News</h4>
      </div>
      <div class="col-lg-6" id="read-news">
        <span class="text-success fs50"><%= @read_news %></span>
        <h4>Read News</h4>
      </div>
    </div>
  </div>
</div>